AWSTemplateFormatVersion: 2010-09-09
Description: Deploying resources using Cloud Formation
Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0873b46c45c11058d
      InstanceType: t2.micro
      SecurityGroupIds:
        - Ref: WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: WebServer
        - Key: Project
          Value: CloudFormation Step By Step
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for the Webservers
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: WebServer Security Group
  SQSQueue:
    Type: AWS::SQS::Queue
    DependsOn: WebServerInstance # waits for webserver instance to be created first
